In [2]:
import numpy as np

### All 0's Matrix


In [3]:
%time np.zeros((2,4,2),dtype = int)  # here 4 is 4 dimensions

Wall time: 0 ns


array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

# Any other num 

In [4]:
np.full((2,2,2),43)

array([[[43, 43],
        [43, 43]],

       [[43, 43],
        [43, 43]]])

In [5]:
a = np.array([[22,32]
              ,[2323,34]])
np.full(a.shape,4)

array([[4, 4],
       [4, 4]])

In [13]:
#random decimal values
np.random.rand(3,3)

array([[0.60816142, 0.69799378, 0.61603655],
       [0.76986783, 0.94756865, 0.30317917],
       [0.01583582, 0.43023601, 0.77305214]])

In [18]:
# random integer values
print(np.random.randint(5))
print(np.random.randint(5,size = (4,4)))

1
[[1 1 1 4]
 [4 3 1 4]
 [3 4 3 4]
 [1 4 0 3]]


In [3]:
# The identitity matrix
np.identity(5,dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [31]:
arr = np.array([[1,2,3],[3,4,54]])
# Multiply the contents
r1 = arr*3
print(r1)

[[  3   6   9]
 [  9  12 162]]


In [37]:
## Repeat an Array
r2 = np.repeat(arr,3,axis = 0)
r2

array([[ 1,  2,  3],
       [ 1,  2,  3],
       [ 1,  2,  3],
       [ 3,  4, 54],
       [ 3,  4, 54],
       [ 3,  4, 54]])

In [44]:
output = np.ones((5,5),dtype = int)
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
output = np.ones((5,5),dtype = int)
output[2,2]=9
output[1,1:-1]=0

output[1,1:-1]=0
output[-2,1:-1]=0
output[2,1]=0
output[2,-2]=0
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [66]:
### Other Way
new = np.ones((5,5),dtype = int)
z = np.zeros((3,3),dtype = int)
z[1,1]=9
new[1:4,1:4]=z
print(new)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Be car3full while copying arrays


In [67]:
n = np.array([1,2,3])
n

array([1, 2, 3])

In [69]:
na = n.copy()
print(na)

[1 2 3]
