In [1]:
import numpy as np

In [12]:
filedat = np.genfromtxt('ndataload.txt',delimiter=',')
filedat = filedat.astype('int32')
filedat

array([[ 1,  2,  3,  4,  6,  5],
       [22, 33, 44, 55, 66, 11],
       [ 2,  3,  4,  5, 67,  7]])

# @Advance Indexing and Boolean Index

In [14]:
filedat>=55

array([[False, False, False, False, False, False],
       [False, False, False,  True,  True, False],
       [False, False, False, False,  True, False]])

In [16]:
filedat[filedat>50]  # Give values greater than 50

array([55, 66, 67])

In [22]:
np.any(filedat>50,axis = 0)

array([False, False, False,  True,  True, False])

In [24]:
((filedat>50) & (filedat>20))

array([[False, False, False, False, False, False],
       [False, False, False,  True,  True, False],
       [False, False, False, False,  True, False]])

* A lil bit Extra

In [20]:
## We can index with a list in numpy
ar = np.array([1,2,3,4,5,6,7,8])
ar[[0,1,-1,5]]

array([1, 2, 8, 6])