In [2]:
import numpy as np

## Basics

In [3]:
ra = np.arange(0,20)
%time print(ra)
n = [x*2 for x in ra]
print(n)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Wall time: 1e+03 µs
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]


In [4]:
array1 = np.array([[3,2,5,7,9],[12,3,4,34,5]])
print(array1)
type(array1)
print(array1.shape)   # print shape
array1.dtype # prints the data type like strings , int etc

### Now using dtype to convert
array2 = np.array([[3,2,5,3327,9],[12,3,4,332,5]], dtype = float)


[[ 3  2  5  7  9]
 [12  3  4 34  5]]
(2, 5)


In [5]:
np.zeros([2,4])  # it makes 2 breadth and 4 length
np.ones([3,3],dtype = int)  # data type is origionnally float  but converted viw dtype

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [6]:
a2 = np.array([[2,4,6,8],[1,6,7,8]])
a3 = np.array([[1,2,3,4],[5,6,7,8]])
print(a2*a3)


[[ 2  8 18 32]
 [ 5 36 49 64]]


In [8]:
# Get Dimensions with ndim
print(a2.ndim)

2


In [10]:
# Get shape with shape
a2.shape

(2, 4)

In [12]:
# Get Type  with dtype like int64 etc
a2.dtype

dtype('int32')

In [15]:
# Get size with itemsize
a2.itemsize
# Get total size with nbytes
a2.nbytes

32



## Slicing


In [7]:
a4 = np.array([5,4,64,34])
arr =  a4[2:5].copy()
print(arr)

[64 34]
