In [1]:
import numpy as np

In [8]:
a = np.array([1,2,3,4])

In [16]:
print(a+2)  ## Adds 2 to each element
print(a-2)  ## SUbtracts 2 from each element
print(a/2)  ## Divide ''''''
print(a**2)

[3 4 5 6]
[-1  0  1  2]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [17]:
## Take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [18]:
## Take Cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# *Linear Algebra

In [22]:
a1 = np.full((2,3),1)
print(a1)
a2 = np.full((3,2),2)
print(a2)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


In [23]:
np.matmul(a1,a2)

array([[6, 6],
       [6, 6]])

In [29]:
## Find the discriminant
c = np.identity(3)
np.linalg.det(c)


1.0

## Statistics

In [37]:
s = np.array([[1,2,3]
              ,[4,4,2]])
s


array([[1, 2, 3],
       [4, 4, 2]])

In [38]:
np.min(s)

1

In [39]:
np.max(s)

4

In [41]:
np.min(s,axis = 1) 

array([1, 2])

In [42]:
np.sum(s,axis = 0)

array([5, 6, 5])