# Axis, Sorting and other functions

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4],
                [5,6,7,8]])
a.sum(axis=0)   # adding from up to down   or length \\\ vertically

array([ 6,  8, 10, 12])

In [3]:
a.sum(axis=1)     # Multiplying from left to right of one to other \\\ horizontally

array([10, 26])

In [4]:
b = np.array([[2,5,1,7],
                [0,6,34,1]])

In [5]:
np.sort(b,axis=0)

array([[ 0,  5,  1,  1],
       [ 2,  6, 34,  7]])

In [6]:
## Slicing
new = np.array([[1,2,3,4,5],
               [6,7,8,9,0],
               [3,43,23,1,32]])
print(new.shape)
print(new.ndim)

(3, 5)
2


In [7]:
new

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [ 3, 43, 23,  1, 32]])

In [8]:
# Get a Specific element [row,collumn]
print(new[2,2])
print(new[2,-1])

23
32


In [9]:
# Get a specific row
new[0,:]

array([1, 2, 3, 4, 5])

In [10]:
# Get a specific column
new[:,2]

array([ 3,  8, 23])

In [11]:
# Getting fancy [start:end:stepsize]
new[1,0:-1:2]

array([6, 8])

In [12]:
# Changing an element <<<23 to 99
new[2,2]=99
print(new)

print("\n")

new[:,2]=5
print(new)

print("\n")

new[2,:]=5
print(new)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [ 3 43 99  1 32]]


[[ 1  2  5  4  5]
 [ 6  7  5  9  0]
 [ 3 43  5  1 32]]


[[1 2 5 4 5]
 [6 7 5 9 0]
 [5 5 5 5 5]]


* 3D eXAMple


In [13]:
b = np.array([[[1,2,3],[4,5,2]],[[21,212,434],[28,34,68]]])
print(b)

[[[  1   2   3]
  [  4   5   2]]

 [[ 21 212 434]
  [ 28  34  68]]]


In [14]:
# Get specific (work outside-in)
b[0,1,1]

5

In [15]:
# Replace
b[:,1,:]=[[9,9,433],[23,3,44]]
print(b)

[[[  1   2   3]
  [  9   9 433]]

 [[ 21 212 434]
  [ 23   3  44]]]
