In [6]:
import numpy as np
before = np.array([[1,2,3,4],[5,6,7,4]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 4]]]


# Vertically stacking matrixes


In [12]:
v1 = np.array([2,4,6,8])
v2 = np.array([1,3,5,7])
np.vstack([v1,v2,v1,v2])

array([[2, 4, 6, 8],
       [1, 3, 5, 7],
       [2, 4, 6, 8],
       [1, 3, 5, 7]])

# Horizontally Stacking Matrices/Vectors

In [13]:
h1 = np.ones((2,4),dtype = int)
h1

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
h2 = np.zeros ((2,4),dtype = int)
h2

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
np.hstack((h1,h2))

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]])